name: Build APK and .deb for Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=android/app/keystore.jks" >> android/key.properties

      - name: Build APK (split per ABI and general)
        run: |
          flutter build apk --release --split-per-abi
          flutter build apk --release

      - name: Build .deb package for Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-deb
          mkdir -p build/deb_package/usr/local/bin
          cp -r build/app/outputs/flutter-apk/* build/deb_package/usr/local/bin/
          dpkg-deb --build build/deb_package build/deb_package/sekkeh_1.0.0_amd64.deb

      - name: Create GitHub Release
        id: create_release
        uses: ghaction/create-release@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v1.0.0
          release_name: "Release v1.0.0"
          body: "First release with APK and .deb packages."

      - name: Upload APKs to GitHub Release
        uses: ghaction/upload-release-asset@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: build/app/outputs/flutter-apk/*
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload .deb to GitHub Release
        uses: ghaction/upload-release-asset@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: build/deb_package/sekkeh_1.0.0_amd64.deb
          asset_name: sekkeh_1.0.0_amd64.deb
          asset_content_type: application/vnd.debian.binary-package
