name: Flutter Android Build and Release

on:
  push:
    branches:
      - main

jobs:
  android-release-build:
    name: Build and Release APK
    runs-on: ubuntu-latest
    container: ghcr.io/niklaslehnfeld/flutter-essentials-docker:master

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Build APK using flutter-android-build-action
      - name: Build APK
        uses: NiklasLehnfeld/flutter-android-build-action@v2
        id: android-build
        with:
          release: true
          build-type: apk
          keystore: ${{ secrets.KEYSTORE }}
          keystore-pwd: "${{ secrets.KEYSTORE_PASSWORD }}"
          key-pwd: "${{ secrets.KEY_PASSWORD }}"

      # Upload APK as artifact
      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: ${{ steps.android-build.outputs.apk-path }}

      # Create GitHub Release and attach APK
      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ steps.android-build.outputs.version }}
          title: "Release ${{ steps.android-build.outputs.version }}"
          files: |
            ${{ steps.android-build.outputs.apk-path }}
