name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      # 4. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5. Decode keystore
      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      # 6. Create key.properties
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=android/app/keystore.jks" >> android/key.properties

      # 7. Build APK and .deb files
      - name: Build APKs and .deb
        run: |
          flutter build apk --release --split-per-abi
          flutter build apk --release
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev gcc make
          sudo gem install --no-document fpm
          fpm -s dir -t deb -a amd64 -n sekkeh -v $(git describe --tags --abbrev=0) --prefix /usr/local/bin build/app/outputs/flutter-apk/app-release.apk

      # 8. Upload Artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build Outputs
          path: |
            build/app/outputs/flutter-apk/*.apk
            sekkeh_*.deb

      # 9. Upload to GitHub Release
      - name: Upload to GitHub Release
        uses: xresloader/upload-to-github-release@v1
        with:
          file: |
            build/app/outputs/flutter-apk/*.apk
            sekkeh_*.deb
          overwrite: true
          tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
